### ISSUE TITLE
URL Title contains characters that are not compatible with KeePass target window regular expressions

### ISSUE THREAD

**Issue by wellread1** [erichgoldman/add-url-to-window-title#1]
KeePass Target Windows support [regular expressions](http://keepass.info/help/base/autotype.html#autowindows).  The field attribute strings that add-url-to-window-title add, contains the left bracket character "[" that is [special character in regular expressions](https://msdn.microsoft.com/en-us/library/az24scfc%28v=vs.110%29.aspx#character_classes) and must be escaped in a regular expression.  

Would it be possible to change the posted attribute strings so that they are compatible with regular expressions; or add an option that either strips, or substitutes alternate characters that are not special characters used in regular expressions?

Note:  I prefer to use the special regular expression character '|' (without the quotes) as my separator sting so I would hope that if an option to strip special characters out of the posted Title were implemented, it would not apply to the separator string.

**Comment by erichgoldman** [comment]
The square brackets were chosen because they would be unique and are illegal with a URL. If you are creating matching rules for these URLs you do not need regular expression in most cases, you can use the simple wildcard instead. I would checkout the [example in the wiki](https://github.com/erichgoldman/add-url-to-window-title/wiki/About---Show-field-attributes-when-a-text-input-field-has-focus#setup-walkthrough---real-world-example-for-httpsloginyahoocom) or you can see in the [demo video @05:54](https://www.youtube.com/watch?v=vGoHoq_JkK4&t=5m54s) the way I would advise setting up your matching rules for use with this extension.

------

For example, here is a generic rule to match for Yahoo Login

    *https://login.yahoo.com/* [Input Name: "username"] [Input ID: "login-username"]*

where the *Title with the Show field attributes when a text input field has focus?* option is enabled, resulting in the window title being set as:

    Yahoo - login - https://login.yahoo.com/ [Input Name: "username"] [Input ID: "login-username"] - Mozilla Firefox

Most users who are comfortable with using regex should be comfortable escaping where needed. Less experienced users will probably be best suited with the simple wildcards.

At this point, because it would require changes in documentation, videos, etc. it does not seem like a good idea to change these characters since they are in the wiki and in videos already and it may confuse less technical users.

For example, you could just match on `.` for each bracket if want to use regex and avoid escaping

    .*https://login.yahoo.com/.* .Input Name: "username". .Input ID: "login-username".*

I considered making the formatting of the field attributes user defined, but there was a concern of overwhelming end users with too many options.

For your use case, can you explain why using basic wildcard matching will not work? If using a regex, you could just match on any character like

**Comment by wellread1** [comment]
Thanks for considering my comments this addon is already my preferred URL in Title poster.

I don't disagree with your points, except to the extent that I don't see the advantage of a relatively verbose construction that makes extra work for a user that uses the KeePass regex Window Title feature when a more compact construction is just as readable and doesn't make more work for users.  It seems to me that the time to make changes is earlier rather than later when the addon is widely adopted.

To use your Yahoo example:

     Yahoo - login - https://login.yahoo.com/ [Input Name: "username"] [Input ID: "login-username"] - Mozilla Firefox
     
     could be
     
     Yahoo - login - https://login.yahoo.com/ - Input Name:username - Input ID:login-username - Mozilla Firefox
Firefox

To my mind the second string is 
 1. Readable
 + More compact (by 6 characters)
 + Doesn't create extra work for users of the KeePass regex Target Window feature.

For that matter if one was willing to sacrifice intelligibility of the field attributes entirely, posting the  least significant figures of a hash of the field attributes, encoded as hexadecimal or case sensitive alpha numeric (base 62) would probably provide all the functionality in a very short string. e.g.
     
    Yahoo - login - https://login.yahoo.com/ - 1D7r - Mozilla Firefox

**Comment by erichgoldman** [comment]
This seems mostly a matter of user preference and would be best left to an option in a future version. I will consider this based on other feedback I receive, if there is a big demand for customization of the string I will consider adding a preference where you can define the exact format like you do in an auto-type rule, e..g, something like

    {Title} - {URL} - {ID} - {NAME}
    {TITLE} - name:{NAME} | id:{ID} <-- {URL}   

In response to the three pints "to my mind" in your post:

   1. I am not sure if this is more readable for all users. I am also not sure if readability matters since many FireFox UIs don't show the full URL and when URLs get very long even on a high resolution, maximized window the attributes may not been seen.
   2. Again, with long URLs these will never be seen and the regex doesn't care how long it is. 
   3. This will depend on how you generate your regex. By making all the separators the same it may make coming up with a regex more complicated.

There are also other ways of doing your regex, for example you could just match against `.*Input Name:username.*` and not match on the square brackets. 

At this time I would consider this to probably be a per user preference which does not impact the actual performance/functionality of the application. While I understand your desire for the cleanest possible regex, inserting a few backslashes to create a rule once is not that much effort relative to all other efforts or even just selecting the parts of the title you want to delete.

**Comment by wellread1** [comment]
Its not a big deal.
