### ISSUE TITLE
Please also add url to http auth windows

### ISSUE THREAD

**Issue by dionorgua** [erichgoldman/add-url-to-window-title#10]
another (now unmainained) addon is able to add url to pages with http auth.

Please consider this as feature request

**Comment by erichgoldman** [comment]
Hello @dionorgua 

Can you please provide me with a link to this other extension.

To be clear, you are talking about when you are prompted to put in your username and password via pop up box  via [HTTP basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication)?

When I test this just now to see how it works for HTTP basic auth, it looks like the page is not loaded before the prompt is shown and the URL is not changed. Therefore, my addon would not be able to address this since it requires the page to be loaded.

My guess without seeing the other extension is that it is a full XUL extension modifying the alert box, using restart-less addon API I do not think this will be possible, but will wait to see this other extension before doing any more research.

**Comment by dionorgua** [comment]
Extension: https://addons.mozilla.org/en-US/firefox/addon/keepass-helper/?src=api

Yes. it's HTTP basic authentication.

**Comment by erichgoldman** [comment]
It looks like that was an XUL based extension. I will have to go back and see what happens in terms of page load time. 

With the restart-less API I was having trouble getting the proper hooks and updates just tracking page load. The action was buggy, so intead I hook into pageShow

From: https://github.com/erichgoldman/add-url-to-window-title/blob/master/lib/main.js#L134

```js
tabs.on('pageshow', function(tab) { 
		addTabWorker(tab); 
}); 
```
Therefore, my addon will not be able to capture the basic auth because it will happen before the page is shown. Since, there are issues with using load in my testing (especially when going back and forward), I will not be able to implement your request in the current code set.

When Mozilla finalizes the move to the more Chrome-like style of extensions, it should be possible to do with load, but for now I will not pursue this with the current codeset.
