### ISSUE TITLE
Problems with https://webmail.strato.com

### ISSUE THREAD

**Issue by loetsinn** [erichgoldman/add-url-to-window-title#14]
Hi eric,
big thanks for your work! I use your extension every day and it helps me a lot.
I have problems with the above website https://webmail.strato.com
If you open the page the URL will be shown in the Title bar for a very short period of time and then overwritten. If you then go into Add-On settings and uncheck/check the "Show full URL?" option the URL will be correctly added by your Add-On but the original Windows title dissappears.
Would be great if you could take a look.

P.S: I use 
Firefox ESR 45.3.0
Add-On v.1.01.1

**Comment by erichgoldman** [comment]
I have done an initial triage. What is happening for me is that the page loads with the URL, the title change, but then it automatically gives focus to the username field. I am noticing that the name is removed:

![t1](https://cloud.githubusercontent.com/assets/3157148/18736256/4f829a00-8053-11e6-9e54-7524c4f314ea.jpg)

however, it is showing the full URL and the input fields. I will try to setup a test box with your specific FF build and investigate further. However, because the extension runs in the same space as JavaScript on the page, there will be some sites that have conflicts.

**Comment by erichgoldman** [comment]
`Repo Maintenance` I am closing tickets for specific sites that are more than three years old, as those sites are likely different now and the problems may no longer exist. If this is still an issue with a modern browser version and the current version of the add on, please respond and we can reopen the ticket.
