### ISSUE TITLE
Enable Multiprocess Firefox support (e10s)

### ISSUE THREAD

**Issue by lieryan** [erichgoldman/add-url-to-window-title#16]
Currently, installing add-url-to-window-title addon will disable multiprocess on Firefox Stable (Firefox 50).

Test procedure:

1. On about:config, created new boolean entry browser.tabs.remote.force-enable=true
2. Enabled add-url-to-window-title addon and restart

Initial result, things seems to be working correctly:

1. URL is shown on title bar
2. Moving to a different tab, the URL part changes as expected
3. Moving to a different window, the URL are shown correctly for each window
4. Opening a new tab then opening a site, window title updates correctly
5. Navigating between pages on different domain works

Tested Platforms: 
- Firefox 50, Linux
- Nightly 53.0a1, 2016-11-21, Linux, shims enabled

**Comment by erichgoldman** [comment]
Hello @lieryan I plan to rewrite the entire extension over the next few months as a [WebExtension since that is the new way](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/). Currently, my extension uses the old framework so it will not be compatible with multi-process.

I currently have no timeline for this, but will announce when that time comes.

**Comment by e00E** [comment]
Bumping as a reminder for you @erichgoldman . Your addon is very useful and I would love to use it with firefox multi process.

**Comment by lieryan** [comment]
@erichgoldman do you have any progress on porting add-url-to-window-title to e10s?

For the moment, I had written [my own rewrite/port of add-url-to-window-title to webextension/e10s](https://github.com/lieryan/add-url-to-window-title-e10s/releases). It is a barebone implementation and hardcoded with my personal/preferred configuration, but I'm publishing it on Github in case anyone might find it useful.

**Comment by erichgoldman** [comment]
> @lieryan - took a look very cool. I regret that this keep getting pushed to the back burner. I think the logic will generally port, the only pain point is that you lose the built in config management with Chrome-style plugins.

**Comment by alerque** [comment]
@e00E Just a note that you can force multi-process mode with this extension enabled. The system _think_ this extension will be a blocker but if you force the multi-process flag it doesn't actually cause any trouble. I've been using it for a couple months successfully.

That being said the rewrite for the web WebExtension system is still necessary for other reasons and I'll be waiting for it here. Thanks for the dev work on this @erichgoldman.

**Comment by monk-time** [comment]
There's a simple WebExtension replacement: [TitleURL](https://addons.mozilla.org/en-US/firefox/addon/url-in-title/)

**Comment by erichgoldman** [comment]
I have recently started the porting efforts. I am starting with Chrome since the API is a bit easier to work with and my main browser is non Vivaldi. I am investigating if I can just use one code base and test the browser for any API differences. I just finished some quick testing tonight in Chrome. Most of the content script is the same. In turns out that options management is actually easier in Chrome WebExtensions.

I need to determine how I am going to setup branches or if I will make a new repo, but I will try to provide some beta releases here before worrying about posting to official repos. I also need to learn new  testing frameworks since the old tests were dependent upon the old Selenium IDE that worked directly in FireFox.

**Comment by erichgoldman** [comment]
Hello @lieryan , I have updated the extension to work with modern Firefox, [please download from AMO](https://addons.mozilla.org/en-US/firefox/addon/add-url-to-window-title/) and let me know if it works for you or if there are bugs.

**Comment by lieryan** [comment]
@erichgoldman sounds cool, I'll take a look at it and play with it over the next few weeks. I will let you know if I had issues.

**Comment by lieryan** [comment]
Seems to be working well from what I can see so far. The only thing that currently prevent me from retiring my reimplementation and permanently switching back to this is to have an option to show the protocol (e.g. `https://`) in the URL, to avoid autotyping to the `http://` version of a site.

I'll see if I can make some time to make a PR for it.

I'll consider this issue completed for now.

**Comment by erichgoldman** [comment]
I am going to open an issue for this, on https://github.com/erichgoldman/add-url-to-window-title/blob/web-extension/managetitle.js#L204 it is calling document.URL which I believe should include the protocol.
