### ISSUE TITLE
[RFE] Add the possibility to show other data in the window title

### ISSUE THREAD

**Issue by claudio-salvio** [erichgoldman/add-url-to-window-title#37]
Hello @erichgoldman 

I think it would be very useful to have the possibility to add other data in the title.
For example, in my case it would be useful to include the date and time of opening the current tab.

Thanks for the extension.

Best regards,
Claudio

**Comment by erichgoldman** [comment]
Hi @claudio-salvio 

This type of customization is not the type of option I would add to the main package due to wide-needs and maintenance. However, you should be able to fork and could inject a timestamp if needed.

> date and time of opening the current tab.

When you say "opening" do you mean a website in the tab or the tab itself? Do you mean changing the domain or just loading any website, those would all be different events to capture.

Note that the <title /> gets updated periodically if there are on page changes from JavaScript, [hashchange](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event) in single page apps, etc. so you would need to consider when and where you would want this to be updated.

Depending on your workflow, I would actually suggest to create a separate add-on and then you could store a lot of different information for all of these different events. 

If for example, your goal is to identify "find the tab about `X` I opened on `Date Y`" It would likely be better to have one spot where all of this would be listed. Though, browser history or an advanced history plugin may be able to provide this for you.
