### ISSUE TITLE
Synology Photostation crashs with activatet plugin

### ISSUE THREAD

**Issue by jo-shi** [erichgoldman/add-url-to-window-title#8]
I can not open my Photostation in Firefox with activated plugin. Everytime the loading of the site stops, and I got an script error. The script doesn't answer. Only if add-url-to-window-title is deactivated the site loads without errors. 

![fehler_add_url_to_title](https://cloud.githubusercontent.com/assets/13527413/11883359/a021e4ce-a512-11e5-95c8-71913668068a.PNG)

**Comment by erichgoldman** [comment]
Thank you for the report. Can you point me to the link for the software you are using so I can install in my dev environment and test for myself?

Please also let me know the version of FireFox you are using.

The line reported has to do with the sanitization of the String. Since this is a single page application, the application may have some script which parses for title changes. There may be an infinite loop, though I will not be able to tell for sure until I can setup some debugging.

**Comment by jo-shi** [comment]
The Software is only available with the hardware. But I can try to set up an external access.

I recognized the issue with Firefox 42 and since yesterday with Firefox 43.

**Comment by erichgoldman** [comment]
Let me get back to you when I have time to setup a remote session and I will reach out to your email, feel free to ping me if I do not get back to you in a timely manner. Mozilla is making some changes to the way that plugins will work so this entire code base may have to be abandoned and re-written. As a result, I am  not investing a lot of time into development of the current code base.

**Comment by erichgoldman** [comment]
`Repo Maintenance` I am closing tickets for specific sites that are more than three years old, as those sites are likely different now and the problems may no longer exist. If this is still an issue with a modern browser version and the current version of the add on, please response and we can reopen the ticket.
